# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-05 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=12)),
                ('location', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('EA', 'Emergency Ambulance'), ('RE', 'Rescue and Evacuation'), ('FF', 'Fire-fighting'), ('GL', 'Gas Leak Control')], max_length=2)),
            ],
        ),
    ]
