# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-05 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CMSApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 33, 46, 98572, tzinfo=utc)),
        ),
    ]
