# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-25 14:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CMSApp', '0003_auto_20190206_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.CharField(default='ASFSD', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='unit_number',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 25, 14, 37, 49, 815392, tzinfo=utc)),
        ),
    ]
