# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-06 07:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CMSApp', '0004_auto_20190325_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nric', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=120)),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('mobile', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='mobile',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='report',
            name='postal_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 7, 9, 19, 902939, tzinfo=utc)),
        ),
    ]
