# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-06 07:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CMSApp', '0005_auto_20190406_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicUser',
            new_name='CivilianData',
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 7, 10, 29, 357402, tzinfo=utc)),
        ),
    ]
