# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-06 08:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CMSApp', '0006_auto_20190406_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civiliandata',
            name='lattitude',
        ),
        migrations.RemoveField(
            model_name='civiliandata',
            name='longitude',
        ),
        migrations.AddField(
            model_name='civiliandata',
            name='region',
            field=models.CharField(default='CENTRAL', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 8, 31, 4, 715909, tzinfo=utc)),
        ),
    ]
