# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-06 08:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CMSApp', '0007_auto_20190406_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civiliandata',
            name='nric',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 8, 41, 49, 762999, tzinfo=utc)),
        ),
    ]
