# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-17 04:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CMSApp', '0008_auto_20190406_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolve_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 4, 56, 55, 464717, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 4, 56, 55, 464717, tzinfo=utc)),
        ),
    ]
