# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-17 15:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CMSApp', '0009_auto_20190417_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='lat',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='lng',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='resolve_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 15, 0, 52, 65016, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 15, 0, 52, 65016, tzinfo=utc)),
        ),
    ]
